### Obtener lista de usuarios
GET http://localhost/apimovil/index.php/user/list?limit=20
Accept: application/json

###

### Obtener Un usuario
GET http://localhost/apimovil/index.php/user/getone?documento=1234567890
Accept: application/json
###

### Eliminar usuario

DELETE http://localhost/apimovil/index.php/user/delete?documento=12344534567
Content-Type: application/x-www-form-urlencoded


###

### Insertar usuario
POST http://localhost/apimovil/index.php/user/create
Content-Type: application/json

{
  "documento": 1234545453,
  "nombre": "Camilo",
  "apellido": "Bolaño",
  "usuario": "camilo",
  "contrasenia": "camilo123"
}

###

### Actualizar usuario
PUT http://localhost/apimovil/index.php/user/update
Content-Type: application/application/json

{
  "documento": 123456789"0,
  "nombre": "Dixon",
  "apellido": "Perez",
  "usuario": "dixon",
  "contrasenia": "dixon123"
}

###

### Iniciar sesión
POST http://localhost/apimovil/index.php/user/login
Content-Type: application/json

{
  "usuario": "dixon",
  "contrasenia": "dixon123"
}
